const CONFIG = {
  SUPABASE_URL: 'https://egwynouadwsgxajeamef.supabase.co',
  SUPABASE_KEY: 'sb_publishable_pH7ues_btOm11lFPfHY4Qg_Ov3fldBQ',
  STORAGE_BUCKET: 'mjTest',
  ADMIN_ID: '1111',
  ADMIN_PW: '1111'
};

const I18N = {
  ko: {
    langName: '한국어',
    flag: '🇰🇷',
    title: '메뉴판',
    price: '원',
    admin: '관리자',
    back: '메뉴판으로',
    logout: '로그아웃',
    login: '관리자 로그인',
    loginBtn: '로그인',
    cancel: '취소',
    idPlaceholder: '아이디',
    pwPlaceholder: '비밀번호',
    loginFail: '아이디 또는 비밀번호가 올바르지 않습니다.',
    addMenu: '메뉴 추가',
    editMenu: '메뉴 수정',
    deleteMenu: '삭제',
    edit: '수정',
    save: '저장',
    confirmDelete: '정말 삭제하시겠습니까?',
    name: '메뉴 이름',
    intro: '메뉴 소개',
    image: '이미지',
    changeLang: '언어 변경',
    noMenu: '등록된 메뉴가 없습니다.',
    loading: '로딩 중...',
    uploadImage: '이미지 업로드',
    selectLang: '언어를 선택해주세요',
    welcome: '어서오세요!'
  },
  en: {
    langName: 'English',
    flag: '🇺🇸',
    title: 'Menu',
    price: 'KRW',
    admin: 'Admin',
    back: 'Back to Menu',
    logout: 'Logout',
    login: 'Admin Login',
    loginBtn: 'Login',
    cancel: 'Cancel',
    idPlaceholder: 'ID',
    pwPlaceholder: 'Password',
    loginFail: 'Invalid ID or password.',
    addMenu: 'Add Menu',
    editMenu: 'Edit Menu',
    deleteMenu: 'Delete',
    edit: 'Edit',
    save: 'Save',
    confirmDelete: 'Are you sure you want to delete?',
    name: 'Menu Name',
    intro: 'Description',
    image: 'Image',
    changeLang: 'Change Language',
    noMenu: 'No menu items found.',
    loading: 'Loading...',
    uploadImage: 'Upload Image',
    selectLang: 'Please select a language',
    welcome: 'Welcome!'
  },
  ja: {
    langName: '日本語',
    flag: '🇯🇵',
    title: 'メニュー',
    price: 'ウォン',
    admin: '管理者',
    back: 'メニューへ',
    logout: 'ログアウト',
    login: '管理者ログイン',
    loginBtn: 'ログイン',
    cancel: 'キャンセル',
    idPlaceholder: 'ID',
    pwPlaceholder: 'パスワード',
    loginFail: 'IDまたはパスワードが正しくありません。',
    addMenu: 'メニュー追加',
    editMenu: 'メニュー編集',
    deleteMenu: '削除',
    edit: '編集',
    save: '保存',
    confirmDelete: '本当に削除しますか？',
    name: 'メニュー名',
    intro: '説明',
    image: '画像',
    changeLang: '言語変更',
    noMenu: 'メニューがありません。',
    loading: '読み込み中...',
    uploadImage: '画像アップロード',
    selectLang: '言語を選択してください',
    welcome: 'いらっしゃいませ！'
  },
  zh: {
    langName: '中文',
    flag: '🇨🇳',
    title: '菜单',
    price: '韩元',
    admin: '管理员',
    back: '返回菜单',
    logout: '退出',
    login: '管理员登录',
    loginBtn: '登录',
    cancel: '取消',
    idPlaceholder: '账号',
    pwPlaceholder: '密码',
    loginFail: '账号或密码不正确。',
    addMenu: '添加菜品',
    editMenu: '编辑菜品',
    deleteMenu: '删除',
    edit: '编辑',
    save: '保存',
    confirmDelete: '确定要删除吗？',
    name: '菜品名称',
    intro: '菜品介绍',
    image: '图片',
    changeLang: '切换语言',
    noMenu: '暂无菜品。',
    loading: '加载中...',
    uploadImage: '上传图片',
    selectLang: '请选择语言',
    welcome: '欢迎光临！'
  }
};
